[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF52833_xxAA"
rustflags = [
  "-C", "linker=flip-link",
  # Code-size optimizations.
  #  "-Z", "trap-unreachable=no",
  #  "-C", "inline-threshold=5",
  #  "-C", "no-vectorize-loops",
  #  "-Z", "emit-stack-sizes",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "debug"
