[package]
name = "s90"
version = "0.1.0"
authors = ["kanghua <kanghua151@msn.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.4"
crc-any = { version = "2.3.5", default-features = false }
defmt = "0.3.0"

[dev-dependencies]
embedded-hal-mock = "0.7.2"
